version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 excursion_system.wsgi"
    tmpfs:
      - /app/ram_db  # Монтируем RAM-директорию
    environment:
      - SECRET_KEY=your-secret-key
      - DEBUG=0
      - DB_ENGINE=django.db.backends.sqlite3
      - DB_NAME=/app/ram_db/db.sqlite3  # Путь в RAM
      - ALLOWED_HOSTS=*
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3